[package]
name = "nubls"
version = "0.1.0"
authors = ["tuxxy <me@johnpacific.com>"]
edition = "2018"

[dependencies.bls12_381]
version = "0.1.1"
features = ["nightly", "endo"]

[dependencies.getrandom]
version = "0.1"

[dependencies.sha2]
version = "0.8.2"
