name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Build NuBLS
      run: cargo build --manifest-path rust-nubls/Cargo.toml --verbose
    - name: Run NuBLS tests
      run: cargo test --manifest-path rust-nubls/Cargo.toml --verbose
